import './globals.css'

export const metadata = {
  title: 'Sean Dundon',
  description: 'Generated by Sean Dundon using Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div className="bg-blue-500 text-white p-4">Header</div>
        {children}
        <div className="bg-blue-500 text-white p-4">Footer</div>
      </body>
    </html>
  )
}
